version: '3.8'

services:
  askimmigrate:
    build: .
    ports:
      - "8088:8088"
    env_file:
      - .env
    volumes:
      - ./backend/config:/app/backend/config:ro
      - ./backend/data:/app/backend/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 3