name: Run Python tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm
      - name: Run tests with coverage
        run: |
          pytest backend/code/tests/ \
            --cov=backend/code \
            --cov-report=term-missing \
            --cov-report=xml:backend/code/tests/coverage.xml \
            --cov-report=json:backend/code/tests/coverage.json
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        if: always()
        with:
          file: ./backend/code/tests/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
